services:
  nanolimbo:
    build:
      context: .
      dockerfile: Dockerfile
    image: nanolimbo
    ports:
      - 65535:65535/tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: nanolimbo_data
        target: /data
        bind:
          create_host_path: true
